### ISSUE TITLE
Thread already started issue

### ISSUE THREAD

**Issue by joseph-roque** [joseph-roque/bowling-companion#114]
Reported in Google Developer console:

```
java.lang.IllegalThreadStateException: Thread already started
    at java.lang.Thread.checkNotStarted(Thread.java:849)
    at java.lang.Thread.start(Thread.java:1059)
    at ca.josephroque.bowlingcompanion.d.run(Unknown Source)
    at java.lang.Thread.run(Thread.java:818)
```

Message from user:

```
put phone in case, came back after frame and program had stopped.
```

**Comment by joseph-roque** [comment]
Looks like this crash was reported again recently:

```
java.lang.IllegalThreadStateException: Thread already started
	at java.lang.Thread.checkNotStarted(Thread.java:849)
	at java.lang.Thread.start(Thread.java:1059)
	at ca.josephroque.bowlingcompanion.d.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:818)
```

App version: 2.1.8
Android version: 6.0
