### ISSUE TITLE
Occasionally shuts down on its own as you back out to select another person

### ISSUE THREAD

**Issue by joseph-roque** [joseph-roque/bowling-companion#98]
Message from user:

```
program occasionally shuts down on its own as you back out to select another person
```

Stack trace from developer console:

```
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.String.substring(int)' on a null object reference
	at ca.josephroque.bowlingcompanion.c.bv.a(Unknown Source)
	at ca.josephroque.bowlingcompanion.c.bv.d(Unknown Source)
	at ca.josephroque.bowlingcompanion.c.cf.onPostExecute(Unknown Source)
	at android.os.AsyncTask.finish(AsyncTask.java:632)
	at android.os.AsyncTask.access$600(AsyncTask.java:177)
	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:645)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:145)
	at android.app.ActivityThread.main(ActivityThread.java:5942)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)
```

**Comment by joseph-roque** [comment]
Due to the changes made in commit e7628d55abe067e924382eb8df608c477fefb556, this issue should no longer appear. If a new report is made by a user or reported in the developer console, this issue can be reopened, but I am deeming this issue closed.
